### ISSUE TITLE
PyAudio Error

### ISSUE THREAD

**Issue by Mayank-11** [Starkeyofficial/Voicepad-Pro-Text-Editor#1]
Bro how to install pyaudio?

**Comment by Starkeyofficial** [comment]
[PyAudio-0.2.11-cp37-cp37m-win_amd64.zip](https://github.com/Starkeyofficial/Voicepad-Pro-Text-Editor/files/5283138/PyAudio-0.2.11-cp37-cp37m-win_amd64.zip)

Unzip it and extract the .whl file. Then open command prompt in the folder where .whl file is present, and type :- pip install PyAudio-0.2.11-cp37-cp37m-win_amd64.whl

**Comment by Mayank-11** [comment]
Bro i got pyaudio but now it is not taking the command

**Comment by Starkeyofficial** [comment]
Is  there any mic issue?
